### ISSUE TITLE
Unable to build this project in Visual Studio 2019

### ISSUE THREAD

**Issue by pradeepngupta** [cube-soft/Cube.Pdf#13]
Hi All,
I have downloaded this repo source code and opened in Visual Studio 2019.
But when i am building this solution in Visual Studio I am getting below errors
![errors](https://user-images.githubusercontent.com/6321439/114070494-afc38780-98bd-11eb-8589-dadfee317740.PNG)

My Visual Studio Version is:
![visualstudio_version](https://user-images.githubusercontent.com/6321439/114070664-db467200-98bd-11eb-946d-d4c200f06ba0.PNG)

Please advise on the errors.
The same errors are visible when i have build the tag version code 3.1.2

**Comment by clown** [comment]
See the following page.
https://stackoverflow.com/questions/51348919/couldnt-process-file-resx-due-to-its-being-in-the-internet-or-restricted-zone-o
