### ISSUE TITLE
Filename containing "."

### ISSUE THREAD

**Issue by mitosagi** [cube-soft/cube.pdf#35]
When using CubePDF to print files with a dot in the filename, the characters after the dot are removed and displayed in the Destination text box.

Alternatively, the characters after the last dot in the filename should be stripped.

If you print 3.141.doc->
Bad 3.pdf
Good 3.141.pdf

**Comment by clown** [comment]
This issue has been improved in 3.3.0. Please update to the latest version and check it.
https://www.cube-soft.jp/cubepdf/

**Comment by mitosagi** [comment]
Thank you for your response, I have confirmed that this has been fixed in 3.3.0.
