### ISSUE TITLE
FR: Save a Print to PDF pdf in the sourcefoulder of the Document by default.

### ISSUE THREAD

**Issue by pjpks** [cube-soft/cube.pdf#42]
It would be handy, if cubepdf would automatically suggest to save the PDF in the same location where the file lies that i Opened. (of there is a file location)

If my Document is at c:\Documents\test\testdocument.docx
i would like cubepdf to suggest c:\Documents\test\testdocument.pdf
as a standard Saving path.

**Comment by clown** [comment]
Unfortunately, CubePDF has no way of knowing the path of the source file.

CubePDF gets the "document name (not the filename or path)" through the Windows virtual printer mechanism.
This name depends on how the application that presses the print button is configured.

**Comment by pjpks** [comment]
Thank you.
