### ISSUE TITLE
how to convert pdf to tiff in azure

### ISSUE THREAD

**Issue by alexgman** [cube-soft/Cube.Pdf#7]
We'd like to be able to convert a multipage PDF to a multipage TIFF within an Azure Function. Is this possible with this library?

**Comment by clown** [comment]
Cube.Pdf.Ghostscript is available for .NET Framework 4.5 or later, and Azure Functions **1.x** supports the .NET Framework.
[Azure Functions runtime versions overview](https://docs.microsoft.com/en-us/azure/azure-functions/functions-versions)

The library uses Ghostscript (gsdll32.dll).
Tutorial for a similar library (using gsdll32.dll in the Azure Functions) is as follows:
[Convert PDF files to PNG Images using Azure Functions](http://lightswitchhelpwebsite.com/Blog/tabid/61/EntryId/3303/Convert-PDF-files-to-PNG-Images-using-Azure-Functions.aspx)
Note that gsdll32.dll is also available for our unofficial NuGet package ([Cube.Native.Ghostscript](https://www.nuget.org/packages/Cube.Native.Ghostscript)).

A sample program to convert PDF to TIFF is as follows:

```cs
// using Cube.Pdf.Ghostscript;

using (var converter = new ImageConverter(Format.Tiff)
{
    // use some more options if needed
}) { converter.Invoke(@"path\to\src.pdf", @"path\to\dest.tiff"); }
```

We will supports the multi-page TIFF format in the future version, but the current version cannot...

**Comment by alexgman** [comment]
has support been implemented for multi-page tiff?

**Comment by clown** [comment]
Multipage tiff is not yet implemented. We will implement it in the future, but no specific plan...
